name: ocx
channels:
  - conda-forge
  - msys2 # for m2-grep
dependencies:
  - python=3.10
  - conda-lock
  - pyyaml=6.0
  - click=8.1.3
  - colorlog=6.7.0
  - fuzzywuzzy=0.18.0
  - tabulate=0.9.0
  - python-Levenshtein=0.20.8
  - lxml=4.9.2
  - requests=2.28.1

  # Development deps
  - Sphinx
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
  - pre-commit
  - black
  - isort
  - autoflake
  - flake8
  - pytest
  - pytest-cov
  - coverage
  - pytest-regressions
  - sphinx-click
  - jake  # Vulnerability scanner for Conda packages
  - bump2version
  - m2w64-make # GNU mMake for windows
  - m2-grep # Grep for windows
  - m2-gawk # awk for windows
  - pip
  # Install any PyPi packages
  - pip:
      # Packages only on PyPi
      - click-shell==2.1 # conda has not version 2.1
