[build-system]
#requires = ["poetry-core>=1.0.0"]
#build-backend = "poetry.core.masonry.api"
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.bandit]
exclude_dirs = ["tests"]
skips = [
    "B320", "B410"  # Skip xml vulnerability as we use lxml
]

