[tool.poetry]
name = "ocx_schema_reader"
version = "0.1.0"
description = "A command line interface for reading and parsing the OCX schema"
authors = ["ocastrup <ole.christian.astrup@dnv.com>"]
license = "MIT"
repository = "https://github.com/OCXStandard/ocx-schema-reader"
documentation = "https://ocx-schema-reader.readthedocs.io/en/latest/index.html"
readme = "README.md"
# Classifiers: http://pypi.python.org/pypi?%3Aaction=list_classifiers
classifiers=[
    # Development Status :: 1 - Planning
    # Development Status :: 2 - Pre-Alpha
    # Development Status :: 3 - Alpha
    # Development Status :: 4 - Beta
    # Development Status :: 5 - Production/Stable
    # Development Status :: 6 - Mature
    # Development Status :: 7 - Inactive
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
]
[tool.poetry.scripts]
ocx_schema_reader = 'main:cli'

[tool.poetry.dependencies]
python = "^3.10"
ocx-xml = "^0.1.0"
PyYAML = "^6.0"
click = "^8.1.3"
colorlog = "^6.7.0"
click-shell = "^2.1"
fuzzywuzzy = "^0.18.0"
tabulate = "^0.9.0"
numpy = "^1.23.5"
python-Levenshtein = "^0.20.8"
pre-commit = "^2.20.0"


[tool.poetry.dev-dependencies]
Sphinx = "^5.3.0"
sphinx-autodoc-typehints = "^1.19.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
#requires = ["setuptools"]
#build-backend = "setuptools.build_meta"
