[tool.poetry]
name = "ocx_schema_reader"
version = "0.1.0"
description = "A command line interface for reading and parsing the OCX schema"
authors = ["ocastrup <ole.christian.astrup@dnv.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
ocx-xml = "^0.1.0"
PyYAML = "^6.0"
click = "^8.1.3"
colorlog = "^6.7.0"
click-shell = "^2.1"
fuzzywuzzy = "^0.18.0"
tabulate = "^0.9.0"
numpy = "^1.23.5"
python-Levenshtein = "^0.20.8"

[tool.poetry.dev-dependencies]
Sphinx = "^5.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
