#  Copyright (c) 2023.  OCX Consortium https://3docx.org. See the LICENSE
formatters:
  fh:
    datefmt: '%d-%m-%Y %I:%M:%S'
    format: '%(asctime)s : %(levelname)s : %(module)s : %(funcName)s : %(message)s'
  std_out:
    format: '%(levelname)s : %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: std_out
    level: INFO
  file:
    class: logging.FileHandler
    filename: ocx-tools.log
    formatter: fh
    level: DEBUG
root:
  handlers:
    - console
    - file
  level: INFO
version: 1
