name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: 3.11.0
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install poetry and update dependencies with make
      run: |
        conda install poetry
        make init
    - name: Run linters
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test-all
